### ISSUE TITLE
What is the category "7"?

### ISSUE THREAD

**Issue by skyguidance** [Thinklab-SJTU/DenseLane#1]
Hi,
Thanks for the great work and providing this lane dataset!
When I exploring the dataset, I found out that in some data that annotation may contains value '7' instead of previously defined annotation spec:

```
annotation { "backgroud": 0, "curb": 1, "lane": 2, "stopline": 3, "crosswalk": 4, "arrow": 5 }
```

What does category '7' stands for? Looking forward to your reply.

**Comment by cxlz** [comment]
Hi, thanks for your attention. Category '7' represents "arrow", we have corrected the annotation spec.

**Comment by skyguidance** [comment]
Thanks for the clarification!
